from deep_translator import GoogleTranslator
import streamlit as st

@st.cache_data
def metni_cevir(text, target_lang):
    if not text: return ""
    if target_lang == 'en': return text
    try:
        return GoogleTranslator(source='auto', target='tr').translate(text)
    except:
        return text

TEXTS = {
    'tr': {
        'title': "KoçFin Pro",
        'sidebar_title': "KoçFin Terminal",
        'lang_select': "Dil / Language",
        'symbol_input': "Varlık Sembolü",
        'period_input': "Zaman Aralığı",
        'layers': "🎨 Grafik Katmanları",
        'layer_sma': "SMA (Ortalamalar)",
        'layer_bollinger': "Bollinger Bantları",
        'layer_signals': "AI Sinyalleri",
        'developer_title': "💀 Kodun Mimarı: Emirhan",
        'developer_desc': "Sistemdeki açıkları arıyor. Finansal Matrix'in ötesini gör.",
        'loading': "Piyasa Verileri İşleniyor...",
        'error_data': "Veri bulunamadı veya sembol hatalı.",
        'error_sys': "Sistem Hatası:",
        'tab_tech': "📊 Teknik Analiz",
        'tab_fund': "🏢 Temel Veriler",
        'tab_news': "📰 Haberler",
        'rsi_label': "RSI Gücü",
        'rsi_overbought': "Aşırı Alım",
        'rsi_oversold': "Aşırı Satım",
        'rsi_neutral': "Nötr",
        'stoch_label': "Stokastik",
        'stoch_sell': "Satış Bölgesi",
        'stoch_buy': "Alış Bölgesi",
        'stoch_wait': "Bekle",
        'bb_label': "Bollinger",
        'bb_expensive': "Pahalı",
        'bb_cheap': "Ucuz",
        'bb_normal': "Normal",
        'trend_label': "Trend",
        'trend_up': "Yükseliş",
        'trend_down': "Düşüş",
        'pe_ratio': "F/K Oranı",
        'market_cap': "Piyasa Değeri",
        'sector': "Sektör",
        'profile_title': "🏢 Şirket Profili",
        'no_data': "Veri Yok",
        'buy_signal': "AL",
        'sell_signal': "SAT",
        'ai_score_title': "AI Teknik Skoru",
        'analysis_logic_title': "🧠 Analiz Mantığı",
        'score_msg_strong_buy': "GÜÇLÜ AL 🚀",
        'score_msg_buy': "AL 🌱",
        'score_msg_neutral': "NÖTR ⚖️",
        'score_msg_sell': "SAT 🔻",
        'score_msg_strong_sell': "GÜÇLÜ SAT 🆘",
        
        # --- RAPOR CÜMLELERİ (YENİ) ---
        'rpt_rsi_low': "RSI Aşırı Satımda ({:.0f}) - Güçlü Al Sinyali",
        'rpt_rsi_high': "RSI Aşırı Alımda ({:.0f}) - Kar Satışı Riski",
        'rpt_rsi_pos': "RSI Pozitif Bölgede (Toparlanma)",
        'rpt_rsi_neg': "RSI Negatif Bölgede (Baskı Var)",
        'rpt_bb_low': "Fiyat Bollinger Alt Bandını Deldi (Tepki Gelebilir)",
        'rpt_bb_high': "Fiyat Bollinger Üst Bandında (Doygunluk)",
        'rpt_golden_cross': "Golden Cross (Yükseliş Trendi) Aktif",
        'rpt_sma_pos': "Fiyat Ortalamaların %{:.1f} Üzerinde (Trend Pozitif)",
        'rpt_sma_neg': "Fiyat Ortalamaların %{:.1f} Altında (Trend Negatif)",
        'rpt_macd_buy': "MACD Alıcılı Seyrediyor",
        'rpt_macd_sell': "MACD Satıcılı Seyrediyor"
    },
    'en': {
        'title': "KocFin Pro",
        'sidebar_title': "KocFin Terminal",
        'lang_select': "Language / Dil",
        'symbol_input': "Asset Symbol",
        'period_input': "Time Period",
        'layers': "🎨 Chart Layers",
        'layer_sma': "SMA (Moving Averages)",
        'layer_bollinger': "Bollinger Bands",
        'layer_signals': "AI Signals",
        'developer_title': "💀 Architect: Emirhan",
        'developer_desc': "Hunting glitches in the system. See beyond the Financial Matrix.",
        'loading': "Processing Market Data...",
        'error_data': "Data not found or invalid symbol.",
        'error_sys': "System Error:",
        'tab_tech': "📊 Technical Analysis",
        'tab_fund': "🏢 Fundamentals",
        'tab_news': "📰 News",
        'rsi_label': "RSI Power",
        'rsi_overbought': "Overbought",
        'rsi_oversold': "Oversold",
        'rsi_neutral': "Neutral",
        'stoch_label': "Stochastic",
        'stoch_sell': "Sell Zone",
        'stoch_buy': "Buy Zone",
        'stoch_wait': "Wait",
        'bb_label': "Bollinger",
        'bb_expensive': "Expensive",
        'bb_cheap': "Cheap",
        'bb_normal': "Normal",
        'trend_label': "Trend",
        'trend_up': "Bullish",
        'trend_down': "Bearish",
        'pe_ratio': "P/E Ratio",
        'market_cap': "Market Cap",
        'sector': "Sector",
        'profile_title': "🏢 Company Profile",
        'no_data': "No Data",
        'buy_signal': "BUY",
        'sell_signal': "SELL",
        'ai_score_title': "AI Technical Score",
        'analysis_logic_title': "🧠 Analysis Logic",
        'score_msg_strong_buy': "STRONG BUY 🚀",
        'score_msg_buy': "BUY 🌱",
        'score_msg_neutral': "NEUTRAL ⚖️",
        'score_msg_sell': "SELL 🔻",
        'score_msg_strong_sell': "STRONG SELL 🆘",

        # --- RAPOR CÜMLELERİ (ENGLISH) ---
        'rpt_rsi_low': "RSI Oversold ({:.0f}) - Strong Buy Signal",
        'rpt_rsi_high': "RSI Overbought ({:.0f}) - Profit Taking Risk",
        'rpt_rsi_pos': "RSI in Positive Zone (Recovery)",
        'rpt_rsi_neg': "RSI in Negative Zone (Pressure)",
        'rpt_bb_low': "Price Pierced Lower Bollinger Band (Reaction Likely)",
        'rpt_bb_high': "Price at Upper Bollinger Band (Saturation)",
        'rpt_golden_cross': "Golden Cross (Uptrend) Active",
        'rpt_sma_pos': "Price is {:.1f}% Above Averages (Positive Trend)",
        'rpt_sma_neg': "Price is {:.1f}% Below Averages (Negative Trend)",
        'rpt_macd_buy': "MACD Showing Buying Pressure",
        'rpt_macd_sell': "MACD Showing Selling Pressure"
    }
}