from deep_translator import GoogleTranslator
import streamlit as st

@st.cache_data
def metni_cevir(text, target_lang):
    if not text: return ""
    if target_lang == 'en': return text
    try:
        return GoogleTranslator(source='auto', target='tr').translate(text)
    except:
        return text


ASSETS_DB = {
    "🔍 Manuel Giriş Yap / Diğer...": "MANUEL",
    "🇹🇷 THYAO - Türk Hava Yolları": "THYAO.IS",
    "🇹🇷 BJKAS - Beşiktaş Futbol Yat.": "BJKAS.IS",
    "🇹🇷 GARAN - Garanti Bankası": "GARAN.IS",
    "🇹🇷 ASELS - Aselsan": "ASELS.IS",
    "🇹🇷 SASA - Sasa Polyester": "SASA.IS",
    "🇹🇷 EREGL - Ereğli Demir Çelik": "EREGL.IS",
    "🇹🇷 SISE - Şişe Cam": "SISE.IS",
    "🇹🇷 KCHOL - Koç Holding": "KCHOL.IS",
    "🇹🇷 FROTO - Ford Otosan": "FROTO.IS",
    "🇹🇷 TUPRS - Tüpraş": "TUPRS.IS",
    "🇹🇷 AKBNK - Akbank": "AKBNK.IS",
    "🇹🇷 ISCTR - İş Bankası (C)": "ISCTR.IS",
    "🇹🇷 YKBNK - Yapı Kredi": "YKBNK.IS",
    "🇹🇷 BIMAS - BİM Mağazalar": "BIMAS.IS",
    "🇹🇷 EKGYO - Emlak Konut": "EKGYO.IS",
    "🇹🇷 KOZAL - Koza Altın": "KOZAL.IS",
    "🇹🇷 PGSUS - Pegasus": "PGSUS.IS",
    "🇹🇷 SAHOL - Sabancı Holding": "SAHOL.IS",
    "🇹🇷 TCELL - Turkcell": "TCELL.IS",
    "🇹🇷 TTKOM - Türk Telekom": "TTKOM.IS",
    "🇹🇷 VESTL - Vestel": "VESTL.IS",
    "🇹🇷 ARCLK - Arçelik": "ARCLK.IS",
    "🇹🇷 PETKM - Petkim": "PETKM.IS",
    "🇹🇷 KONTR - Kontrolmatik": "KONTR.IS",
    "🇹🇷 Hektaş - HEKTS": "HEKTS.IS",
    "🇺🇸 AAPL - Apple Inc.": "AAPL",
    "🇺🇸 TSLA - Tesla Inc.": "TSLA",
    "🇺🇸 MSFT - Microsoft Corp.": "MSFT",
    "🇺🇸 AMZN - Amazon.com": "AMZN",
    "🇺🇸 GOOGL - Alphabet (Google)": "GOOGL",
    "🇺🇸 NVDA - NVIDIA Corp.": "NVDA",
    "🇺🇸 META - Meta Platforms (Facebook)": "META",
    "🇺🇸 NFLX - Netflix": "NFLX",
    "🇺🇸 AMD - Advanced Micro Devices": "AMD",
    "🇺🇸 INTC - Intel Corp.": "INTC",
    "🇺🇸 COIN - Coinbase Global": "COIN",
    "🇺🇸 GME - GameStop": "GME",
    "₿ BTC-USD - Bitcoin": "BTC-USD",
    "Ξ ETH-USD - Ethereum": "ETH-USD",
    "◎ SOL-USD - Solana": "SOL-USD",
    "🐶 DOGE-USD - Dogecoin": "DOGE-USD",
    "✖ XRP-USD - Ripple": "XRP-USD",
    "BNB-USD - Binance Coin": "BNB-USD",
    "AVAX-USD - Avalanche": "AVAX-USD",
    "🟡 XAU/USD - Altın (Ons)": "GC=F",
    "⚪ XAG/USD - Gümüş (Ons)": "SI=F",
    "🛢️ Brent Petrol": "BZ=F",
    "💵 USD/TRY - Dolar/TL": "TRY=X",
    "💶 EUR/TRY - Euro/TL": "EURTRY=X"
}

TEXTS = {
    'tr': {
        'title': "KoçFin Pro",
        'sidebar_title': "KoçFin Terminal",
        'lang_select': "Dil / Language",
        'symbol_select': "Varlık Ara (Hisse, Kripto...)",
        'symbol_manual': "Varlık Sembolünü Yazın (Örn: AAPL, THYAO.IS)",
        'period_input': "Zaman Aralığı",
        'layers': "🎨 Grafik Katmanları",
        'layer_sma': "SMA (20/50 - Kısa Vade)",
        'layer_ema': "EMA 100 (Trend Kalkanı) 🛡️",
        'layer_bollinger': "Bollinger Bantları",
        'layer_signals': "AI Sinyalleri",
        'developer_title': "💀 Kodun Mimarı: Emirhan",
        'developer_desc': "Sistemdeki açıkları arıyor. Finansal Matrix'in ötesini gör.",
        'loading': "Piyasa Verileri İşleniyor...",
        'error_data': "Veri bulunamadı veya sembol hatalı.",
        'error_sys': "Sistem Hatası:",
        'tab_tech': "📊 Teknik Analiz",
        'tab_fund': "🏢 Temel Veriler",
        'tab_news': "📰 Haberler",
        'rsi_label': "RSI Gücü",
        'rsi_overbought': "Aşırı Alım",
        'rsi_oversold': "Aşırı Satım",
        'rsi_neutral': "Nötr",
        'stoch_label': "Stokastik",
        'stoch_sell': "Satış Bölgesi",
        'stoch_buy': "Alış Bölgesi",
        'stoch_wait': "Bekle",
        'bb_label': "Bollinger",
        'bb_expensive': "Pahalı",
        'bb_cheap': "Ucuz",
        'bb_normal': "Normal",
        'trend_label': "Trend",
        'trend_up': "Yükseliş",
        'trend_down': "Düşüş",
        'pe_ratio': "F/K Oranı",
        'market_cap': "Piyasa Değeri",
        'sector': "Sektör",
        'profile_title': "🏢 Şirket Profili",
        'no_data': "Veri Yok",
        'buy_signal': "AL",
        'sell_signal': "SAT",
        'dip_buy': "💎",
        'peak_sell': "⛔",
        'ai_score_title': "AI Teknik Skoru",
        'analysis_logic_title': "🧠 Analiz Mantığı",
        'score_msg_strong_buy': "GÜÇLÜ AL 🚀",
        'score_msg_buy': "AL 🌱",
        'score_msg_neutral': "NÖTR ⚖️",
        'score_msg_sell': "SAT 🔻",
        'score_msg_strong_sell': "GÜÇLÜ SAT 🆘",
        'rpt_rsi_low': "RSI Dipte ({:.0f}) - Tepki Alımı Bekleniyor 💎",
        'rpt_rsi_high': "RSI Zirvede ({:.0f}) - Düzeltme Gelebilir ⚠️",
        'rpt_rsi_pos': "RSI Pozitif Bölgede (Güçlü)",
        'rpt_rsi_neg': "RSI Negatif Bölgede (Zayıf)",
        'rpt_bb_low': "Fiyat Bollinger Altında - UCUZLUK FIRSATI 🛒",
        'rpt_bb_high': "Fiyat Bollinger Üstünde - AŞIRI PAHALI 💸",
        'rpt_golden_cross': "Golden Cross (Yükseliş Trendi) Aktif",
        'rpt_sma_pos': "Fiyat Ortalamaların %{:.1f} Üzerinde (Trend Pozitif)",
        'rpt_sma_neg': "Fiyat Ortalamaların %{:.1f} Altında (Trend Negatif)",
        'rpt_macd_buy': "MACD Al Sinyali Üretti",
        'rpt_macd_sell': "MACD Sat Sinyali Üretti",
        'rpt_ema_pos': "Fiyat EMA 100 Üzerinde (Trend Boğa) 🐂",
        'rpt_ema_neg': "Fiyat EMA 100 Altında (Trend Ayı) 🐻"
    },
    'en': {
        'title': "KocFin Pro",
        'sidebar_title': "KocFin Terminal",
        'lang_select': "Language / Dil",
        'symbol_select': "Search Asset (Stock, Crypto...)",
        'symbol_manual': "Enter Ticker Symbol (e.g., AAPL, THYAO.IS)",
        'period_input': "Time Period",
        'layers': "🎨 Chart Layers",
        'layer_sma': "SMA (20/50 - Short Term)",
        'layer_ema': "EMA 100 (Trend Shield) 🛡️",
        'layer_bollinger': "Bollinger Bands",
        'layer_signals': "AI Signals",
        'developer_title': "💀 Architect: Emirhan",
        'developer_desc': "Hunting glitches in the system. See beyond the Financial Matrix.",
        'loading': "Processing Market Data...",
        'error_data': "Data not found or invalid symbol.",
        'error_sys': "System Error:",
        'tab_tech': "📊 Technical Analysis",
        'tab_fund': "🏢 Fundamentals",
        'tab_news': "📰 News",
        'rsi_label': "RSI Power",
        'rsi_overbought': "Overbought",
        'rsi_oversold': "Oversold",
        'rsi_neutral': "Neutral",
        'stoch_label': "Stochastic",
        'stoch_sell': "Sell Zone",
        'stoch_buy': "Buy Zone",
        'stoch_wait': "Wait",
        'bb_label': "Bollinger",
        'bb_expensive': "Expensive",
        'bb_cheap': "Cheap",
        'bb_normal': "Normal",
        'trend_label': "Trend",
        'trend_up': "Bullish",
        'trend_down': "Bearish",
        'pe_ratio': "P/E Ratio",
        'market_cap': "Market Cap",
        'sector': "Sector",
        'profile_title': "🏢 Company Profile",
        'no_data': "No Data",
        'buy_signal': "BUY",
        'sell_signal': "SELL",
        'dip_buy': "💎",
        'peak_sell': "⛔",
        'ai_score_title': "AI Technical Score",
        'analysis_logic_title': "🧠 Analysis Logic",
        'score_msg_strong_buy': "STRONG BUY 🚀",
        'score_msg_buy': "BUY 🌱",
        'score_msg_neutral': "NEUTRAL ⚖️",
        'score_msg_sell': "SELL 🔻",
        'score_msg_strong_sell': "STRONG SELL 🆘",
        'rpt_rsi_low': "RSI Bottomed ({:.0f}) - Bounce Expected 💎",
        'rpt_rsi_high': "RSI Peaked ({:.0f}) - Correction Likely ⚠️",
        'rpt_rsi_pos': "RSI in Positive Zone (Strong)",
        'rpt_rsi_neg': "RSI in Negative Zone (Weak)",
        'rpt_bb_low': "Price Below Bollinger - BARGAIN OPPORTUNITY 🛒",
        'rpt_bb_high': "Price Above Bollinger - OVERPRICED 💸",
        'rpt_golden_cross': "Golden Cross (Uptrend) Active",
        'rpt_sma_pos': "Price is {:.1f}% Above Averages (Positive Trend)",
        'rpt_sma_neg': "Price is {:.1f}% Below Averages (Negative Trend)",
        'rpt_macd_buy': "MACD Buy Signal",
        'rpt_macd_sell': "MACD Sell Signal",
        'rpt_ema_pos': "Price Above EMA 100 (Bull Trend) 🐂",
        'rpt_ema_neg': "Price Below EMA 100 (Bear Trend) 🐻"
    
    }
}